sudo: false
dist: bionic 



install:
  - git clone https://github.com/gflags/gflags
  - cd gflags
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH=~/usr .. && make -j8 all install 

  - cd ~
  - git clone https://github.com/google/glog
  - cd glog
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH=~/usr .. && make -j8 all install


  - cd ~
  - git clone https://github.com/google/googletest
  - cd glog
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH=~/usr .. && make -j8 all install 


# Enable C++ support
language: cpp
script:
  - cd ~
  - rm -rf gflags
  - rm -rf glog
  - rm -rf googletest
  - rm -rf build
  - git clone https://github.com/behnamasadi/gtest_gmock/
  - cd gtest_gmock
  - mkdir build
  - cd build
  - cmake .. && make -j8
